name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Go Lambda binary
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/bootstrap ./cmd

      - name: Zip Lambda binary
        run: |
          cd build
          zip main.zip bootstrap

      - name: Upload Lambda code to AWS
        run: |
          aws lambda update-function-code \
            --function-name config \
            --zip-file fileb://build/main.zip \
            --region ap-northeast-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2